# Composition for development

version: '2'

services:
  odoo:
    tty: true
    stdin_open: true
    image: idiotoflinux/mdpodoo
    ports:
      - 8069
    depends_on:
      - db
    volumes:
      - ${WEBAPP_STORAGE_HOME}/data-odoo:/data/odoo
      - ${WEBAPP_STORAGE_HOME}/data-odoo-pytest-cache:/odoo/.cache
      # to speed build of image customise your .dockerignore (this is an help there)
      - ${WEBAPP_STORAGE_HOME}/odoo:/odoo
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD="100%Koffie"
      - RUNNING_ENV=dev
      - LOG_HANDLER=:WARN
      - MARABUNTA_MODE=demo  # could be 'full' for the db with all the data
      - MARABUNTA_ALLOW_SERIE=True  # should not be set in production

  db:
    image: postgres:9.6
    ports:
      - 5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ${WEBAPP_STORAGE_HOME}/data-db:/var/lib/postgresql/data

  # can be useful for dev when longpolling is required
  nginx:
    image: camptocamp/odoo-nginx:11.0-1.3.0
    ports:
      - 80:80
    depends_on:
      - odoo

